# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6096bc83ff1406ffaad38f215efaac0b541453fa8c6119002be4625ac86e313a9e51e01506d5db4189f945adfb603e488c49260ae4dcc629dda709f5225f28d3

test:
  secret_key_base: fa7bbcc3a91f3139e954f79b1c8bffb7dc7a9afecedddb375cf797d473a6630ae64c3e356b22d67695d23469e2f13acc7d98ede6d6e9251863c0b14b0f200ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
